spring.application.name=SmartInventoryAndOrderManagementSystem
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/restdb
spring.datasource.username=root
spring.datasource.password=deepSQL@2004
spring.jpa.hibernate.ddl-auto=update

